name: Caching README

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache README
      id: cache-reaadme
      uses: actions/cache@v4
      with:
        path: README.md
        key: readme