name: Caching README

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ['self-hosted', 'dev']

    steps:
    - uses: actions/checkout@v4

    - name: Cache README
      id: cache-reaadme
      uses: actions/cache@v4
      with:
        path: README.md
        key: readme