---
name: 'gpu-runner'
on:
  workflow_dispatch:
defaults:
  run:
    shell: 'bash'
permissions:
  id-token: write
  contents: read
jobs:
  nvidia:
    runs-on: ['hyperenv-beta', 'public-vpc-g4dn']
    steps:
    - uses: 'actions/checkout@v4'
    - name: 'NVIDIA SMI output'
      run: |
        nvidia-smi