name: rds-migration-flyway
on:
  workflow_dispatch:
  push:
jobs:
  rds-migration-flyway:
    runs-on: [hyperenv, demo]
    steps:
    - uses: docker://amazonlinux:2
      with:
        args: >-
          yum install tree -y
          tree /github
    - name: migrate
      uses: docker://redgate/flyway:10
      with:
        args: >-
          migrate
          -configFiles="/github/workspace/rds-migration-flyway/flyway.toml"
          -locations="filesystem:/github/workspace/rds-migration-flyway/migrations/"
          -url="${{ secrets.FLYWAY_URL }}"
          -user="${{ secrets.FLYWAY_USER }}"
          -password="${{ secrets.FLYWAY_PASSWORD }}"