name: rds-migration-flyway
on:
  workflow_dispatch
jobs:
  rds-migration-flyway:
    runs-on: [hyperenv, demo]
    steps:
    - name: migrate
      uses: docker://redgate/flyway:10
      with:
        args: >-
          migrate
          -workingDirectory="${{ github.workspace }}/rds-migration-flyway/migrations/"
          -url="${{ secrets.FLYWAY_URL }}"
          -user="${{ secrets.FLYWAY_USER }}"
          -password="${{ secrets.FLYWAY_PASSWORD }}"