name: rds-migration-flyway
on:
  workflow_dispatch:
  push:
jobs:
  rds-migration-flyway:
    runs-on: [hyperenv, demo]
    steps:
    - uses: actions/checkout@v4
    - name: migrate
      uses: docker://redgate/flyway:10
      with:
        args: >-
          migrate
          -url="${{ secrets.FLYWAY_URL }}"
          -user="${{ secrets.FLYWAY_USER }}"
          -password="${{ secrets.FLYWAY_PASSWORD }}"