name: rds-migration-flyway
on:
  workflow_dispatch:
  push:
jobs:
  rds-migration-flyway:
    runs-on: [hyperenv, demo]
    steps:
    - run: 'ls -la /opt/hyperenv/_work/hyperenv-examples'
    - run: 'ls -la /opt/hyperenv/_work/hyperenv-examples/hyperenv-examples'
    - uses: docker://amazonlinux:2
      with:
        args: >-
          ls -la /github/workspace
    - name: migrate
      uses: docker://redgate/flyway:10
      with:
        args: >-
          migrate
          -configFiles="/github/workspace/rds-migration-flyway/flyway.toml"
          -locations="filesystem:/github/workspace/rds-migration-flyway/migrations/"
          -url="${{ secrets.FLYWAY_URL }}"
          -user="${{ secrets.FLYWAY_USER }}"
          -password="${{ secrets.FLYWAY_PASSWORD }}"